---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define standard packages
  set_fact:
      python_ml_packages: "{{ __python_ml_packages | list }}"
  when: node_packages is not defined

- name: include os-specific setup
  include_tasks: "setup-{{ ansible_os_family }}.yml"
